# 第二回レポート
1810083 井上悠香

シグモイド関数

In [8]:
import matplotlib.pylab as plt
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

ソフトマックス関数

In [9]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

3層マルチパーセプトロンによるNN

In [10]:
import numpy as np
def identity_function(x):
    return x

def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    W2=network['W2']
    b2=network['b2']
    W3=network['W3']
    b3=network['b3']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    a2 =np.dot(z1,W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3)+b3
    y = identity_function(a3)
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.31682708 0.69627909]]


バッチ処理

In [13]:
import numpy as np
import random  

network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
print(x)
print(y)

[[0.67723327 0.09954505]
 [0.89745072 0.07287157]
 [0.98518225 0.24331173]
 ...
 [0.94381402 0.37882077]
 [0.1619652  0.52008253]
 [0.63148073 0.96248472]]
[[0.31682708 0.69627909]]


# 感想
活性化関数を使うことで、重みをつけて足し合わせたデータの重要度を測れることがわかった。初め、活性化関数が出てきたとき何ができるのかよくわからなかったが、活性化関数を使うことで人間の扱いやすいデータに変換しているのだと思った。今は一旦、あくまで道具のようなものなのだと思う。
今回の演習で、行列を使うことのありがたみがわかった。for文を回さなくても一層におけるニューロンが計算できるのはとても楽だった。